/** Mapping noms français → code ISO pour les drapeaux */
export const TEAM_FLAGS: Record<string, string> = {
  Mexique: "mx",
  "Afrique du Sud": "za",
  "Corée du Sud": "kr",
  Tchéquie: "cz",
  Canada: "ca",
  "Bosnie-Herzégovine": "ba",
  "États-Unis": "us",
  Paraguay: "py",
  Qatar: "qa",
  Suisse: "ch",
  Brésil: "br",
  Maroc: "ma",
  Haïti: "ht",
  Écosse: "gb-sct",
  Australie: "au",
  Turquie: "tr",
  Allemagne: "de",
  Curaçao: "cw",
  "Pays-Bas": "nl",
  Japon: "jp",
  "Côte d'Ivoire": "ci",
  Équateur: "ec",
  Suède: "se",
  Tunisie: "tn",
  Espagne: "es",
  "Cap-Vert": "cv",
  Belgique: "be",
  Égypte: "eg",
  "Arabie saoudite": "sa",
  Uruguay: "uy",
  Iran: "ir",
  "Nouvelle-Zélande": "nz",
  France: "fr",
  Sénégal: "sn",
  Irak: "iq",
  Norvège: "no",
  Argentine: "ar",
  Algérie: "dz",
  Autriche: "at",
  Jordanie: "jo",
  Portugal: "pt",
  "RD Congo": "cd",
  Angleterre: "gb-eng",
  Croatie: "hr",
  Ghana: "gh",
  Panama: "pa",
  Ouzbékistan: "uz",
  Colombie: "co",
};

/** CDN lipis/flag-icons — SVG 4x3, toutes tailles, codes subdivisions OK */
export function getFlagUrl(team: string): string {
  const code = TEAM_FLAGS[team] ?? "un";
  return `https://flagicons.lipis.dev/flags/4x3/${code}.svg`;
}
